---
meta:
  name:    docker-buildx-resource
  target:  ohio-sw
  url:     https://ci2.starkandwayne.com

  initial_version: 0.5.0

  docker:
    root: ""

  git:
    email:  ((git-commit-email))
    name:   ((git-commit-name))

  dockerhub:
    username: ((dockerhub-username))
    email:    ((dockerhub-email))
    password: ((dockerhub-password))
    repository: (( concat meta.github.owner "/" meta.name ))

  aws:
    bucket:      (( grab meta.pipeline ))
    region_name: us-east-2
    access_key:  ((aws-access-key))
    secret_key:  ((aws-secret-key))

  github:
    owner:  starkandwayne
    repo:   docker-buildx-resource
    branch: master
    private_key:  ((github-private-key))
    access_token: ((github-access-token))

  slack:
    webhook:       ((slack-webhook))
    username:      ((slack-username))
    icon:          ((slack-icon-url))
    channel:       "#docker-buildx-resource"
